JacksonFiveProperties/Controllers/MaintencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JacksonFiveProperties.Models;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;
using System.Drawing.Drawing2D;
using PagedList;

namespace JacksonFiveProperties.Controllers
{
    [Authorize]
    public class MaintencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Maintences
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            List<Maintence> TransVMlist = new List<Maintence>(); // to hold list of Customer and order details

            var query = (from trans in db.Maintences
                         join prop in db.Properties on trans.PropertyID equals prop.ID
                         where trans.isUsed == true
                         select new
                         {
                             Maintence = trans,
                             Property = prop,
                             address = (prop.Address)
                         });
            if (!String.IsNullOrEmpty(searchString))
            {
                query = (from trans in db.Maintences
                         join prop in db.Properties on trans.PropertyID equals prop.ID
                         where trans.isUsed == true
                         && trans.addss.Contains(searchString)
                         select new
                         {
                             Maintence = trans,
                             Property = prop,
                             address = (prop.Address)
                         });
            }
            switch (sortOrder)
            {
                case "name_desc":
                    query = query.OrderByDescending(s => s.address);
                    break;
                case "Date":
                    query = query.OrderBy(s => s.Maintence.Date);
                    break;
                case "date_desc":
                    query = query.OrderByDescending(s => s.Maintence.Date);
                    break;
                default:
                    query = query.OrderBy(s => s.address);
                    break;
            }
            foreach (var item in query)

            {

                Maintence objcvm = new Maintence(); // ViewModel
                objcvm.Amount = item.Maintence.Amount;
                objcvm.Time = item.Maintence.Time;
                objcvm.dateModified = item.Maintence.dateModified;
                objcvm.By = item.Maintence.By;
                objcvm.Description = item.Maintence.Description;
                objcvm.ID = item.Maintence.ID;
                objcvm.isUsed = item.Maintence.isUsed;
                objcvm.PropertyID = item.Maintence.PropertyID;
                objcvm.Parts = item.Maintence.Parts;
                objcvm.LaborHours = item.Maintence.LaborHours;
                objcvm.Date = item.Maintence.Date;
                objcvm.addss = item.address;

                TransVMlist.Add(objcvm);

            }
            
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(TransVMlist.ToPagedList(pageNumber, pageSize));
        }

        // GET: Maintences/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maintence maintence = await db.Maintences.FindAsync(id);
            if (maintence == null)
            {
                return HttpNotFound();
            }
            return View(maintence);
        }

        // GET: Maintences/Create
        public ActionResult Create()
        {
            ViewBag.data = db.Properties.ToList();
            return View();
        }

        // POST: Maintences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Date,PropertyID,Time,By,Description,Parts,LaborHours,Amount,dateModified,isUsed")] Maintence maintence)
        {
            try
            {
                TempData["Success"] = null;
                TempData["Error"] = null;
                if (ModelState.IsValid)
                {
                    var property = Request["property"];
                    maintence.PropertyID = Convert.ToInt32(property);
                    maintence.isUsed = true;
                    db.Maintences.Add(maintence);
                    await db.SaveChangesAsync();
                    TempData["Success"] = "Saved Successfully!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                ModelState.AddModelError("Error!", ex.Message.ToString());
            }


            return View(maintence);
        }

        // GET: Maintences/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maintence maintence = await db.Maintences.FindAsync(id);
            if (maintence == null)
            {
                return HttpNotFound();
            }
            var model = new MaintenceViewModel()
            {
                Maintence = db.Maintences.Where(x => x.isUsed == true).FirstOrDefault(s => s.ID == id),
                
            };

            model.Propertyselect = new SelectList(db.Properties.Where(x => x.IsUsed == true).ToList(), "ID", "Address", maintence.PropertyID);
            return View(model);
        }

        // POST: Maintences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(MaintenceViewModel vmmaintence)
        {
            try
            {
                TempData["Success"] = null;
                TempData["Error"] = null;
                if (ModelState.IsValid)
                {
                    
                    var maintnece = db.Maintences.FirstOrDefault(n => n.ID == vmmaintence.Maintence.ID);

                    maintnece.isUsed = true;
                    maintnece.Time = vmmaintence.Maintence.Time;
                    maintnece.By = vmmaintence.Maintence.By;
                    maintnece.Description = vmmaintence.Maintence.Description;
                    maintnece.Parts = vmmaintence.Maintence.Parts;
                    maintnece.Date = vmmaintence.Maintence.Date;
                    maintnece.Amount = vmmaintence.Maintence.Amount;
                    maintnece.LaborHours = vmmaintence.Maintence.LaborHours;
                    maintnece.PropertyID = vmmaintence.Maintence.PropertyID;
                    //db.Entry(maintnece).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    TempData["Success"] = "Saved Successfully!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                ModelState.AddModelError("Error!", ex.Message.ToString());
            }
            return View(vmmaintence);
        }

        // GET: Maintences/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maintence maintence = await db.Maintences.FindAsync(id);
            if (maintence == null)
            {
                return HttpNotFound();
            }
            return View(maintence);
        }

        // POST: Maintences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                TempData["Success"] = null;
                TempData["Error"] = null;
                Maintence maintence = await db.Maintences.FindAsync(id);
                maintence.isUsed = false;
                //db.Maintences.Remove(maintence);
                await db.SaveChangesAsync();
                TempData["Success"] = "Deleted Successfully!";
                return RedirectToAction("Index");
            }
            catch 
                (Exception ex)
            {
                    TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                    ModelState.AddModelError("Error!", ex.Message.ToString());
                }
            return View("Error");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

JacksonFiveProperties/Views/Maintences/Create.cshtml
@model JacksonFiveProperties.Models.Maintence

@{
    ViewBag.Title = "Create";
    ViewBag.File = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Maintence Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @id = "date" } })

                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("property", new SelectList(@ViewBag.data, "ID", "Address"), "--  Select Address  --", new { @class = "form-control dropdown", Value = @ViewBag.data, required = "required" })
                @*@Html.EditorFor(model => model.PropertyID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.PropertyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date'>
                    @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control", @id = "datetimepicker3" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span>
                </div>
                    <p class="h6">
                        @Html.Label("example: 12:30 AM", new { @class = "blockquote-footer" })
                    </p>
                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parts, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-inline col-md-10">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @id = "currency" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LaborHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.LaborHours, 10, 80, new { htmlAttributes = new { @class = "form-control" } }),
                @Html.ValidationMessageFor(model => model.LaborHours, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/inputmask")
    @*<script src="~/Scripts/jquery.timepicker.min.js"></script>
        <link rel="stylesheet" href="~/Content/jquery.timepicker.css" />*@
    <script type="text/javascript">
        $(document).ready(function () {
            $("#date").inputmask('99/99/9999');

            $("#currency").inputmask({
                max: '99999999.99',
                alias: 'currency',
                prefix: ''
                //allowPlus: false,
                //        autoUnmask: true,
            });
        });
        $("#datetimepicker3").inputmask('99:99 AA');
    </script>

        <script type="text/javascript">if ('@TempData["Success"]' != '') { toastr.success('@TempData["Success"]') }</script>
        <script type="text/javascript">if ('@TempData["Error"]' != '') { toastr.error('@TempData["Error"]') }</script>

}

JacksonFiveProperties/Views/Maintences/Delete.cshtml
@model JacksonFiveProperties.Models.Maintence

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Maintence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaborHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaborHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isUsed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isUsed)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
@section Scripts {

    <script type="text/javascript">if ('@TempData["Success"]' != '') { toastr.success('@TempData["Success"]') }</script>
    <script type="text/javascript">if ('@TempData["Error"]' != '') { toastr.error('@TempData["Error"]') }</script>
}

JacksonFiveProperties/Views/Maintences/Details.cshtml
@model JacksonFiveProperties.Models.Maintence

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Maintence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaborHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaborHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isUsed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isUsed)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JacksonFiveProperties/Views/Maintences/Edit.cshtml
@model JacksonFiveProperties.Models.MaintenceViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Maintence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Maintence.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maintence.Date, new { htmlAttributes = new { @class = "form-control", @id = "date" } })
                @Html.ValidationMessageFor(model => model.Maintence.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.PropertyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("property", new SelectList(@ViewBag.data, "ID", "Address"), "--  Select Address  --", new { @class = "form-control dropdown", Value = @ViewBag.data, required = "required" })*@
                @*@Html.EditorFor(model => model.Maintence.PropertyID, Model.Propertyselect, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(mv => mv.Maintence.PropertyID, Model.Propertyselect, new { @class = "form-control dropdown" })
                @Html.ValidationMessageFor(model => model.Maintence.PropertyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maintence.Time, new { htmlAttributes = new { @class = "form-control", @id = "datetimepicker3" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
                <p class="h6">
                    @Html.Label("example: 12:30 AM", new { @class = "blockquote-footer" })
                </p>
                @Html.ValidationMessageFor(model => model.Maintence.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maintence.By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maintence.By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Maintence.Description, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maintence.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.Parts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Maintence.Parts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maintence.Parts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.LaborHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Maintence.LaborHours, 10, 80, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Maintence.LaborHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Maintence.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="form-inline col-md-10">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                @Html.EditorFor(model => model.Maintence.Amount, new { htmlAttributes = new { @class = "form-control", @id = "currency" } })
                @Html.ValidationMessageFor(model => model.Maintence.Amount, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/inputmask")
    <script type="text/javascript">
        $(document).ready(function () {
            $("#date").inputmask('99/99/9999');

            $("#currency").inputmask({
                max: '99999999.99',
                alias: 'currency',
                prefix: ''
                //allowPlus: false,
                //        autoUnmask: true,
            });
        });
        $("#datetimepicker3").inputmask('99:99 AA');
    </script>
    <script type="text/javascript">if ('@TempData["Success"]' != '') { toastr.success('@TempData["Success"]') }</script>
    <script type="text/javascript">if ('@TempData["Error"]' != '') { toastr.error('@TempData["Error"]') }</script>
}

JacksonFiveProperties/Views/Maintences/UploadFile.cshtml
@*@model IEnumerable<JacksonFiveProperties.Models.ImageModel>
    @{
        ViewBag.Title = "UploadFile";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>UploadFile</h2>
    @using (Html.BeginForm("UploadFile", "Maintences", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div>
            @Html.TextBox("file", "", new { type = "file" }) <br />

            <input type="submit" value="Upload" class="btn btn-primary" />

            @ViewBag.Message

        </div>


    }*@
@model  IEnumerable<JacksonFiveProperties.Models.FileModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload File</title>
</head>
<body>
    @using (Html.BeginForm("UploadFile", "Maintences", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="postedFile" />
        <input type="submit" id="btnUpload" value="Upload" />
    }
    @using (Html.BeginForm("DownloadFile", "Maintences", FormMethod.Post))
    {
        <input type="hidden" id="hfFileId" name="FileId" />
        <input type="submit" id="btnDownload" value="Download" style="display:none" />
    }
    <hr />
    <table cellpadding="0" cellspacing="0" class="table">
        <tr>
            @*<th style="width:50px">File ID</th>*@
            <th style="width:120px">File Name</th>
            <th style="width:80px">Download</th>
            <th style="width:80px">Delete</th>
        </tr>
        @if (Model.Count() > 0)
        {
            foreach (var file in Model)
            {

                <tr>
                    @*<td>@file.Id</td>*@
                    <td>@file.Name</td>
                    <td><a href="javascript:;" onclick="DownloadFile(@file.Id)">Download</a></td>
                    @*<td><a href="javascript:;" onclick="Delete(@file.Id)" id="btndelete">Delete</a></td>*@
                    <td>@Html.ActionLink("Delete", "DeleteFile", new { id = file.Id, mid = file.MaintenceID })</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
        }
    </table>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        function DownloadFile(fileId) {
            debugger;
            $("#hfFileId").val(fileId);
            $("#btnDownload")[0].click();
        };
        function Delete(fileId) {

            //$("#btndelete").click(function (fileId) {
            $("#hfFileId").val(fileId);
            $.ajax({
                url: '/Maintences/DeleteFile',
                method: 'DELETE',
                data: {
                    ID: $('#hfFileId').val()
                },
                success: function (id) {
                    debugger;
                }
            });
            //});
        }
    </script>
</body>
</html>
@section Scripts {

    <script type="text/javascript">if ('@TempData["Success"]' != '') { toastr.success('@TempData["Success"]') }</script>
    <script type="text/javascript">if ('@TempData["Error"]' != '') { toastr.error('@TempData["Error"]') }</script>
}