JacksonFiveProperties/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JacksonFiveProperties.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View(); 
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JacksonFiveProperties/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JacksonFiveProperties.Models;
using PagedList;

namespace JacksonFiveProperties.Controllers
{
    [Authorize]
    public class PropertiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Properties
        public ActionResult Index1(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var propertyindex = db.Properties.Where(x => x.IsUsed.Equals(true));
            if (!String.IsNullOrEmpty(searchString))
            {
                propertyindex = db.Properties.Where(x => x.Address.Contains(searchString) && x.IsUsed.Equals(true));
            }

                switch (sortOrder)
            {
                case "name_desc":
                    propertyindex = propertyindex.OrderByDescending(s => s.Address.ToString());
                    break;
                default:
                    propertyindex = propertyindex.OrderBy(s => s.Address);
                    break;
            }
            //  return View(db.Properties.Where(x => x.IsUsed.Equals(true)).ToList());
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(propertyindex.ToPagedList(pageNumber, pageSize));
        }

        // GET: Properties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        // GET: Properties/Create
        public ActionResult Create1()
        {
            var lldID = db.Landlords.ToList();
            if (lldID != null)
            {
                ViewBag.data = lldID;
            }
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create1([Bind(Include = "ID,Address,City,State,Zip")] Property property, string Datas)
        {
            try
            {
                TempData["Success"] = null;
                TempData["Error"] = null;
                if (ModelState.IsValid)
                {
                    var value = Request["fullname"];
                    property.IsUsed = true;                    
                    db.Properties.Add(property);
                    db.SaveChanges();
                    PropLandLrd propLand = new PropLandLrd();
                    
                    property.LandlordID = Convert.ToInt32(value);
                    propLand.PropertyID = Convert.ToInt32(property.ID);
                    db.PropLandLrds.Add(propLand);
                    db.SaveChanges();
                    TempData["Success"] = "Property saved successfully!";
                    return RedirectToAction("Index1");

                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                ModelState.AddModelError("Error!", ex.Message.ToString());
            }
            return View(property);
        }

        // GET: Properties/Edit/5
        public ActionResult Edit1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }

            var model = new PropViewModel()
            {
                Property =  db.Properties.Where(x => x.IsUsed == true).FirstOrDefault(s => s.ID == id),
                PropLandLrd = db.PropLandLrds.FirstOrDefault(s => s.PropertyID == id),
            };
            model.owner = new SelectList(db.Landlords.Where(x => x.IsUsed == true).ToList(), "ID", "fullname", model.PropLandLrd.LandlordID);
            ViewBag.owner = new SelectList(db.Landlords.Where(x => x.IsUsed == true).ToList(), "ID", "fullname", model.PropLandLrd.LandlordID);
            return View(model);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit1( PropViewModel propertymodel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["Success"] = null;
                    TempData["Error"] = null;
                    var prop = db.Properties.FirstOrDefault(n => n.ID == propertymodel.Property.ID);
                    var propLrd = db.PropLandLrds.FirstOrDefault(n => n.PropertyID == propertymodel.Property.ID);

                    prop.Address = propertymodel.Property.Address;
                    prop.City = propertymodel.Property.City;
                    prop.IsUsed = true;
                    prop.State = propertymodel.Property.State;
                    prop.Zip = propertymodel.Property.Zip;
                    propLrd.LandlordID = Convert.ToInt32(propertymodel.PropLandLrd.LandlordID);

                    //db.Entry(property).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["Success"] = "Property saved successfully!";
                    return RedirectToAction("Index1");
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                ModelState.AddModelError("Error!", ex.Message.ToString());
            }
            return View(propertymodel);
        }

        // GET: Properties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Property property = db.Properties.Find(id);
            if (property == null)
            {
                return HttpNotFound();
            }
            return View(property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                TempData["Success"] = null;
                TempData["Error"] = null;
                Property property = db.Properties.Find(id);
                property.IsUsed = false;
                db.Entry(property).State = EntityState.Modified;
                //db.Properties.Remove(property);
                db.SaveChanges();
                TempData["Success"] = "Property deleted successfully!";
                return RedirectToAction("Index1");
            }
            catch 
            {
                TempData["Error"] = "Oops! Something Unexpected happend, data did not save!";
                return View("Error");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JacksonFiveProperties/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message </h3> 

<p>Use this area to provide additional information.</p>
   

JacksonFiveProperties/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JacksonFiveProperties/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1> 
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <button type="button" onclick="location.href='@Url.Action( "Index1", "Properties")'" class="btn btn-default">Property
        </button>
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2> 
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

    <div class="jumbotron">
        <h1 class="display-3">Hello!</h1>
        <p class="lead">Welcome to Jackson 5 Properties Data Warehouse.</p>
        <hr class="my-4">
        <p>Please use the navigation bar to access information.</p>
        @*<p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>*@
    </div>